### ISSUE TITLE
fails to build on Ubuntu 22.04 LTS

### ISSUE THREAD

**Issue by RealDoigt** [c2lang/c2c_native#1]
I tried to build the repo because I was curious how that would work and it seemed simple, unfortunately, it failed for me on the second step. I got these errors: 
```c2
building c2c
Warning: environment variable C2_LIBDIR not set!
error: cannot open (null)/libc/manifest.yaml: No such file or directory

parsing c2c
parsing took 15154 usec
common/file/reader.c2:18:8: error: unknown module 'libc_fcntl'
import libc_fcntl local;
```

**Comment by bvdberg** [comment]
Indeed, the library environment was not correctly described in the README.md. Now the libraries are no longer
in the c2c (C++) archive, but in a separate archive. Please pull the new changes on master and follow the README.md. Let me know if it still fails to build. Thanks for noticing!
