### ISSUE TITLE
Segfault on various uses of tab characters

### ISSUE THREAD

**Issue by SchokiCoder** [c2lang/c2c_native#10]
These lines cause segfaults respectively:
```
a	;
a;	
	c_int a =	2;
```

Interestingly enough, when changing the type from c_int to i32 or bool it doesn't segfault anymore.
_(For now, i have only tested c_int, bool and i32)_

**Comment by bvdberg** [comment]
Is that the whole file? Can you attach an exact file (or push on a branch). I cannot reproduce this yet

**Comment by bvdberg** [comment]
Fixed! It was not the parsing, but the diagnostic message (unknown variable a) that caused the crash
