### ISSUE TITLE
Unclear documentation

### ISSUE THREAD

**Issue by RealDoigt** [c2lang/c2c_native#12]
Hello,

I know it's several months later, but I'm facing the same error as prior.
How do I set the libraries correctly? The readme simply says "To find the libraries c2c needs an environment variable, please update env.sh to your setting and run". This assumes that the reader has knowledge and know-how he may not necessarily have. It needs more instructions with more details:

1) Which line(s) needs to be updated in the file?
2) How to set those variable(s)?
3) Etc. for each variable if the process differs between them.

Edit: naturally, if there are other dependencies required for compilation or execution, it should be in there. Someone managed to figure it out for me and now it says it needs something called "libc" to compile a c2 program. I have a package called libc on my system but it doesn't seem to want that libc, or perhaps it cannot find it?

**Comment by bvdberg** [comment]
I can understand your issue, so I've written an INSTALL.md that just described the literal steps needed.
Please follow those, if you still run into this issues, please open a new issue here. Thanks!

**Comment by RealDoigt** [comment]
Thank you!
